version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}'
      - 'MONGO_HOST=${MONGO_HOST}'
      - 'MONGO_PORT=${MONGO_PORT}'
      - 'MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}'
      - 'MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}'
      - 'APP_MONGO_USER=${APP_MONGO_USER}'
      - 'APP_MONGO_PASS=${APP_MONGO_PASS}'
      - 'APP_MONGO_DB=${APP_MONGO_DB}'
    ports:
      - '27017:27017'
    volumes:
      - './mongo-scripts/:/docker-entrypoint-initdb.d/'
